# Generated by Django 5.2.17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

	initial = True

	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name='Organization',
			fields=[
				('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('name', models.CharField(max_length=200)),
				('slug', models.SlugField(max_length=80, unique=True)),
				('is_active', models.BooleanField(default=True)),
			],
			options={'ordering': ('name',)},
		),
		migrations.CreateModel(
			name='OrganizationMembership',
			fields=[
				('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20)),
				('is_active', models.BooleanField(default=True)),
				('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organization.organization')),
				('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
			],
			options={'ordering': ('organization', 'user')},
		),
		migrations.AddConstraint(
			model_name='organizationmembership',
			constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_organization_membership'),
		),
	]