# Generated by Django 5.2.17 on 2026-08-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaveapplication',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
