import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ('employees', '0003_employee_department_employee_employment_type_and_more'), ('organization', '0003_costcenter_department_employmenttype_position'), ('talent', '0001_initial')]
    operations = [
        migrations.CreateModel(name='Announcement', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('title', models.CharField(max_length=180)), ('message', models.TextField()), ('published_at', models.DateTimeField(blank=True, null=True)), ('expires_on', models.DateField(blank=True, null=True)), ('is_published', models.BooleanField(default=False)), ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='organization.organization'))]),
        migrations.CreateModel(name='ApprovalRequest', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('category', models.CharField(max_length=50)), ('title', models.CharField(max_length=180)), ('payload', models.JSONField(blank=True, default=dict)), ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)), ('decision_note', models.TextField(blank=True)), ('decided_at', models.DateTimeField(blank=True, null=True)), ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approvals', to=settings.AUTH_USER_MODEL)), ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='organization.organization')), ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_approvals', to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='EmployeeDocument', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('title', models.CharField(max_length=180)), ('category', models.CharField(default='Policy', max_length=80)), ('body', models.TextField(blank=True)), ('file_url', models.URLField(blank=True)), ('requires_acknowledgement', models.BooleanField(default=False)), ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=12)), ('expires_on', models.DateField(blank=True, null=True)), ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_documents', to='organization.organization'))]),
        migrations.CreateModel(name='ExternalConnector', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('name', models.CharField(max_length=120)), ('kind', models.CharField(choices=[('PAYROLL', 'Payroll/tax provider'), ('BENEFITS', 'Benefits carrier'), ('ESIGN', 'E-signature provider'), ('BACKGROUND', 'Background checks'), ('IDENTITY', 'Identity provider'), ('MESSAGING', 'Email/SMS provider')], max_length=20)), ('endpoint', models.URLField(blank=True)), ('configuration', models.JSONField(blank=True, default=dict, help_text='Store non-secret connector settings only.')), ('is_enabled', models.BooleanField(default=False)), ('last_sync_at', models.DateTimeField(blank=True, null=True)), ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_connectors', to='organization.organization'))]),
        migrations.CreateModel(name='ProfileChangeRequest', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('requested_changes', models.JSONField(default=dict)), ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)), ('remarks', models.TextField(blank=True)), ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_change_requests', to='employees.employee')), ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='Project', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('code', models.CharField(max_length=30)), ('name', models.CharField(max_length=140)), ('is_billable', models.BooleanField(default=False)), ('is_active', models.BooleanField(default=True)), ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='organization.organization'))]),
        migrations.CreateModel(name='OffboardingTask', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('title', models.CharField(max_length=160)), ('due_date', models.DateField(blank=True, null=True)), ('completed_at', models.DateTimeField(blank=True, null=True)), ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)), ('offboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='talent.offboardingrecord'))]),
        migrations.CreateModel(name='DocumentAcknowledgement', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('acknowledged_at', models.DateTimeField(auto_now_add=True)), ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='operations.employeedocument')), ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_acknowledgements', to='employees.employee'))]),
        migrations.CreateModel(name='CompensationChange', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('effective_date', models.DateField()), ('previous_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)), ('proposed_salary', models.DecimalField(decimal_places=2, max_digits=12)), ('reason', models.CharField(max_length=180)), ('approval', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensation_change', to='operations.approvalrequest')), ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_changes', to='employees.employee'))]),
        migrations.CreateModel(name='TimesheetEntry', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('work_date', models.DateField()), ('hours', models.DecimalField(decimal_places=2, max_digits=5)), ('notes', models.TextField(blank=True)), ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=12)), ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)), ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_entries', to='employees.employee')), ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timesheet_entries', to='operations.project'))]),
        migrations.AddConstraint(model_name='project', constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_project_code_per_org')),
        migrations.AddConstraint(model_name='documentacknowledgement', constraint=models.UniqueConstraint(fields=('document', 'employee'), name='unique_document_acknowledgement')),
    ]
